import test from "node:test";
import assert from "node:assert/strict";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join, relative } from "node:path";

// detail.html / reader.html are now mounted by esbuild-bundled dist/{detail,reader}.bundle.js React
// tree (Phase 1 / 2b cutover), but the pure logic retained under src/js/job-detail, src/js/reader still uses
// string literals referencing DOM id/class, esbuild does not do such checks: id renaming, typos, deleted CSS classes will only
// silently fail at runtime (dom/query.js guards swallow null). This test cross-checks: job-detail / reader
// Every "detail-*" / "reader-*" string literal appearing in JS within the directory must be found in the corresponding page HTML's
// id/class, class definitions in src/styles, JSX in src/pages/{detail,reader} (id=.../className=...),
// or JS constructed elements (id="...").
//
// home page (index.html / src/pages/home) is not included in this file: home has no single id prefix convention (each feature
// domains have their own naming), use tests/home-app-component.test.mjs (rendering HomeApp asserting contract ids) + each domain's
// *-component.test.mjs (e.g. recent-jobs-library-component / status-card-component, etc.),
// render actual React trees asserting DOM contracts) cover, which is a stronger check than scanning string literals here — directly rendering
// Components assert against real DOM, not guessing ownership by scanning source strings. Phase 4 review confirms this judgment still holds,
// no need to include home in this file.

const PROJECT_ROOT = process.cwd();
const STYLES_ROOT = join(PROJECT_ROOT, "src/styles");

// Confirmed historical legacy references (runtime elements/classes indeed do not exist). Before adding new items, must manually confirm,
// and state the reason; once references regain ownership, the hygiene test below will force removal from here.
const KNOWN_ORPHANS = {
  "src/js/job-detail": Object.freeze([
// class generated by template, no corresponding rule in src/styles (unstyled div)
    "detail-artifact-meta",
  ]),
  "src/js/reader": Object.freeze([]),
};

const PAGES = [
  {
    jsDir: "src/js/job-detail",
    prefix: "detail",
    htmlFile: "detail.html",
// After Phase 1 cutover, detail.html only has #detail-root mount point, page skeleton
// (id/class) is now rendered by React tree: ownership validation needs to scan new world JSX
// id="..." and className="..." (retained old pure logic still writes these nodes by id).
    jsxDir: "src/pages/detail",
  },
  {
    jsDir: "src/js/reader",
    prefix: "reader",
    htmlFile: "reader.html",
// After Phase 2b cutover, reader.html only has #reader-root mount point, page skeleton
// (id/class) is now rendered by React tree (following detail precedent to scan new world JSX).
    jsxDir: "src/pages/reader",
  },
];

function walkFiles(dir, extension) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      results.push(...walkFiles(fullPath, extension));
    } else if (entry.endsWith(extension)) {
      results.push(fullPath);
    }
  }
  return results;
}

function collectLiterals(jsFiles, prefix) {
  const pattern = new RegExp(`["'](${prefix}-[a-z0-9-]+)["']`, "g");
  const literals = new Map();
  for (const file of jsFiles) {
    const text = readFileSync(file, "utf8");
    for (const match of text.matchAll(pattern)) {
      const literal = match[1];
      if (!literals.has(literal)) {
        literals.set(literal, relative(PROJECT_ROOT, file));
      }
    }
  }
  return literals;
}

function collectOwnership(htmlText, jsTexts, cssText, jsxTexts = []) {
  const ids = new Set(
    [...htmlText.matchAll(/id="([a-z0-9-]+)"/g)].map((m) => m[1]),
  );
  for (const text of [...jsTexts, ...jsxTexts]) {
    for (const match of text.matchAll(/\bid\s*=\s*"([a-z0-9-]+)"/g)) {
      ids.add(match[1]);
    }
  }
  const classes = new Set();
  for (const match of htmlText.matchAll(/class="([^"]+)"/g)) {
    for (const name of match[1].split(/\s+/)) {
      classes.add(name);
    }
  }
// React page skeleton: JSX className is equivalent to old HTML class ownership
  for (const text of jsxTexts) {
    for (const match of text.matchAll(/className="([^"]+)"/g)) {
      for (const name of match[1].split(/\s+/)) {
        classes.add(name);
      }
    }
  }
  for (const match of cssText.matchAll(/\.([a-z0-9][a-z0-9-]*)/g)) {
    classes.add(match[1]);
  }
  return { ids, classes };
}

function isOwned(literal, ownership) {
  if (ownership.ids.has(literal) || ownership.classes.has(literal)) {
    return true;
  }
// Composite id pattern, e.g. showReaderPaneEmpty uses "reader-pdf" to compose "reader-pdf-wrap"
  const family = `${literal}-`;
  for (const id of ownership.ids) {
    if (id.startsWith(family)) {
      return true;
    }
  }
  return false;
}

function analyzePage({ jsDir, prefix, htmlFile, jsxDir = "" }) {
// After TS migration, source files are .ts/.tsx; still compatible with residual .js/.jsx
  const jsFiles = [
    ...walkFiles(join(PROJECT_ROOT, jsDir), ".ts"),
    ...walkFiles(join(PROJECT_ROOT, jsDir), ".js"),
  ];
  const jsTexts = jsFiles.map((file) => readFileSync(file, "utf8"));
  const jsxTexts = jsxDir
    ? [
      ...walkFiles(join(PROJECT_ROOT, jsxDir), ".tsx"),
      ...walkFiles(join(PROJECT_ROOT, jsxDir), ".jsx"),
      ...walkFiles(join(PROJECT_ROOT, jsxDir), ".ts"),
      ...walkFiles(join(PROJECT_ROOT, jsxDir), ".js"),
    ].map((file) => readFileSync(file, "utf8"))
    : [];
  const htmlText = readFileSync(join(PROJECT_ROOT, htmlFile), "utf8");
  const cssText = walkFiles(STYLES_ROOT, ".css")
    .map((file) => readFileSync(file, "utf8"))
    .join("\n");
  const literals = collectLiterals(jsFiles, prefix);
  const ownership = collectOwnership(htmlText, jsTexts, cssText, jsxTexts);
  return { literals, ownership };
}

for (const page of PAGES) {
  const allowlist = new Set(KNOWN_ORPHANS[page.jsDir]);

  test(`${page.jsDir} 的 ${page.prefix}-* 引用在 ${page.htmlFile}/样式/模板中有归属`, () => {
    const { literals, ownership } = analyzePage(page);
assert.ok(literals.size > 0, `No ${page.prefix}-* literals found in ${page.jsDir}, check scanning logic`);
    const orphans = [];
    for (const [literal, file] of literals) {
      if (!isOwned(literal, ownership) && !allowlist.has(literal)) {
orphans.push(`{literal} (first seen in {file})`);
      }
    }
    assert.deepEqual(
      orphans,
      [],
`The following references do not exist in {page.htmlFile}'s id/class, src/styles class definitions, or JS constructed elements,+
        `会在运行时静默失效:\n  ${orphans.join("\n  ")}`,
    );
  });

test(`KNOWN_ORPHANS list in {page.jsDir} has no stale entries, () => {
    const { literals, ownership } = analyzePage(page);
    const stale = [];
    for (const literal of allowlist) {
      if (!literals.has(literal) || isOwned(literal, ownership)) {
        stale.push(literal);
      }
    }
    assert.deepEqual(
      stale,
      [],
The following KNOWN_ORPHANS entries are no longer orphans (references deleted or restored ownership), please remove from list: {stale.join(", ")}`,
    );
  });
}
